apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-frontend
  template:
    metadata:
      labels:
        app: news-frontend
    spec:
      containers:
      - name: news-frontend
        image: news-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: news-frontend-service
spec:
  selector:
    app: news-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
